### ISSUE TITLE
Failed to build serde_derive with cargo tarpaulin

### ISSUE THREAD

**Issue by amentis** [xd009642/tarpaulin#81] opened 2018-01-22 10:11 UTC
cargo --version
cargo 0.26.0-nightly (6a8eb71f6 2018-01-13)
rustc --version
rustc 1.25.0-nightly (97520ccb1 2018-01-21)
gcc --version
gcc (GCC) 7.2.1 20171224
uname -a
Linux d3l40 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux

What was tried:
cargo tarpaulin -v on a crate, that includes serde_derive
Fail:
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/amentis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib"
....
 "/home/amentis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b511442e4b89828a.rlib" "-Wl,-Bdynamic" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util" "-shared" "-no-pie"
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/crt1.o: In function `_start':
          (.text+0x20): undefined reference to `main'
          collect2: error: ld returned 1 exit status

**Comment by Libbum** [comment] 2018-01-22 11:03
This is a known problem I think: #23

**Comment by xd009642** [comment] 2018-01-22 18:41
Yeah this is a duplicate, and unfortunately I think the bug is going to have to be patched in rustc. Might be time for me to contribute to the rust compiler for the first time...

Closing as it's a duplicate of #23.

**Closed by xd009642** 2018-01-22 18:41 UTC
Labels: bug, duplicate
