### ISSUE TITLE
Some misses in coverage

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#136] opened 2018-07-19 13:57 UTC
On my last coverage I've spotted a few oddities in the coverage:

### an `else` alone on its line is the only uncovered line of the function

see https://codecov.io/gh/Smithay/wayland-rs/src/master/wayland-commons/src/socket.rs#L33

The content of both branches of an `if` is marked as covered, but the line containing only `} else {` is marked as uncovered.

### a `let v =` expression split onto two lines

see https://codecov.io/gh/Smithay/wayland-rs/src/master/wayland-commons/src/socket.rs#L198

the code is basically

```rust
let var =
        something();
```

The line containing `let var =` is marked as uncovered, while the second one is marked as covered.

### chained operations on iterators are not consistently 

see https://codecov.io/gh/Smithay/wayland-rs/src/master/wayland-commons/src/wire.rs#L243

I have something like

```rust
let arguments = signature
    .iter()
    .map(|a| {
        /* some very big closure */
    })
    .collect();
```

the `let ...` lines and `.map(` are marked covered, while the `iter()` and `collect()` ones are marked as not covered.

### a match arm marked uncovered while its contents are covered

see https://codecov.io/gh/Smithay/wayland-rs/src/master/wayland-commons/src/wire.rs#L259

It is something like

```rust
match val {
    Match1 => something(),
    Match2 => {
        another_thing();
    }
}
```

the line with `another_thing()` is marked covered, by the line with `Match2 => {` is marked as not covered.

EDIT: Checklist!

- [ ] Inconsistent coverage with macros like `assert_eq!`
- [ ] fix `collect::<_>()?` and other issues with `?` on function calls
- [ ] inline asm! - potentially just ignore this and ensure the block is hit.
- [ ] unsafe blocks can still be weird, look into `let x = unsafe {\n`
- [x] match arms with constants in
- [ ] lines in match which are just the pattern 
- [x] multiline let statements
- [ ] lines only containing `else`
- [ ] Handle fact attributes can be attached to any expression
- [ ] `PhantomData`

**Comment by xd009642** [comment] 2018-07-19 19:55
So most of these I'm already aware of via #63 the `let` expression one I kind of expected but hadn't seen any examples.

With the DWARF tables multiple instructions map to the same line and some of them if instrumented will be hit some won't. I know that can fix the chained operators on iterators from some experiments I've done. However, I haven't yet found any sources on what instructions to prefer or a way of determining the best instruction analytically...

I'm going to keep trying to figure it out but any help anyone can offer is appreciated

**Comment by TheDan64** [comment] 2018-10-15 20:53
Are there still plans to build a regression test suite? And what are the best ways for the community to help you improve coverage?

**Comment by xd009642** [comment] 2018-10-15 21:00
Well right now I'm running tarpaulin on faktory-rs so I can go over the reports and look for any coverage issues.

At some point I would like the integration tests to be a lot better, completely overhaul the projects. It would need an amount of work into figuring out what coverage should look like. Obviously some of the like the proc-macro test and simple-project currently serve a purpose.

I think a good starting point for tests would be a project for each expression in https://docs.rs/syn/0.15.11/syn/enum.Expr.html that demonstrates every form each expression could take and what is expected from coverage. I'll try and do some tests like this some point this week to work as a template and we'll see where it goes from there. If I do I'll post any follow up on #54 so as not to distract too much from this issue (although they are obviously interlinked)

**Comment by jeremydavis519** [comment] 2018-10-26 23:50
I have some more data to add to this from my own recent test. This is using the published version of tarpaulin, so some of these may have been fixed already. I've marked the lines that tarpaulin said were covered:

```rust
impl Parse for CustomAssert {
>   fn parse(input: ParseStream) -> parse::Result<Self> {
        let expr = input.call(Expr::parse)?; // Required expression
        if input.parse::<Token![,]>().is_ok() { // Optional message
>           let message = input.call(Punctuated::parse_separated_nonempty)?;
>           Ok(CustomAssert { expr, message })
>       } else {
>           Ok(CustomAssert { expr, message: Punctuated::new() })
        }
    }
}
```

It seems like the line numbers reported within `fn parse` are offset by 2 from where they should be. I'd expect to see that the `let` and `if` lines were hit, and the code I was testing didn't test the `else` branch at all, so those lines shouldn't be hit. I checked the output a few times to be sure, and those are definitely the lines it's reporting.

But the hits after this snippet in the same file were where I expected, so I don't know if the hits were actually being reported 2 lines ahead of where they should be. The other option is that the first two lines weren't registered and the tracer mistakenly grouped the `else` branch with something else.

**Comment by dgriffen** [comment] 2019-02-07 22:38
One thing I'd like to add is that the `--ignore-panics` flag doesn't appear to work for match arms in tests with panics. See here: https://codecov.io/gh/dgriffen/nestor/src/master/nestor/src/handler.rs#L242

**Comment by jonhoo** [comment] 2019-03-02 19:03
@xd009642 here's another coverage test for [`inferno`](https://github.com/jonhoo/inferno) that has some anomalies that may serve as handy test-cases: https://codecov.io/gh/jonhoo/inferno/src/master/src/collapse/perf.rs

**Comment by calidion** [comment] 2019-03-04 17:48
panic lines are missed too.

**Comment by jonhoo** [comment] 2019-03-08 16:36
I think #185 is related to this.

**Comment by orium** [comment] 2019-03-10 20:22
Another one: on inlined functions, the first line with the `fn` keywork will be reported as not covered.  This was tested with both the latest release as of this time (0.7.0) and with `develop` 26202208.

To reproduce:

```rust
#[inline(always)]
fn foo() {
    println!()
}

#[test]
fn test_foo() {
    foo();
}
```

Line #2 (`fn foo() {`) will be reported as not covered.  (The body is correctly reported as covered.)

Ref #79

**Comment by jonhoo** [comment] 2019-03-11 14:04
It looks like `break` is also [missed](https://codecov.io/gh/jonhoo/inferno/src/1ec9283bac896cee90296109abdacc4d87e4f265/src/collapse/dtrace.rs#L60).

**Comment by andybitter** [comment] 2019-03-12 14:06
...aaaand another one:

miss:
   ```
pub fn receive_event(&mut self, event: Event) {
        let old_state = self.state.clone();

        match event {
            Event::NewClimateData(climate) => {
                self.state = self.state.determine_next_state_by_climate_input(climate)
            }
            Event::DeactivateAlarmRequested => {  // THIS LINE IS MISSED
                self.state = self.state.determine_next_state_for_deactivate_alarm_requested()
            }
        }

        if old_state != self.state {
            self.trigger_output_for_new_state();
        }
    }
```

works fine:
```
pub fn receive_event(&mut self, event: Event) {
        let old_state = self.state.clone();

        match event {
            Event::NewClimateData(climate) => {
                self.state = self.state.determine_next_state_by_climate_input(climate)
            }
            Event::DeactivateAlarmRequested => { self.state = self.state.determine_next_state_for_deactivate_alarm_requested() } // THIS WORKS FINE
        }

        if old_state != self.state {
            self.trigger_output_for_new_state();
        }
    }
```

swapping the two match arms also works fine:
```
pub fn receive_event(&mut self, event: Event) {
        let old_state = self.state.clone();

        match event {
            Event::DeactivateAlarmRequested => {
                self.state = self.state.determine_next_state_for_deactivate_alarm_requested()
            }
            Event::NewClimateData(climate) => {
                self.state = self.state.determine_next_state_by_climate_input(climate)
            }

        }

        if old_state != self.state {
            self.trigger_output_for_new_state();
        }
    }
```

**Comment by dweidenfeld** [comment] 2019-05-09 09:48
Same issue with log statements in matches ;)
See: ![Coverage Report](https://i.imgur.com/QXEoQPz.png)

**Comment by YaLTeR** [comment] 2019-09-02 20:33
Multiline `let` is marked as solved, but I'm hitting that issue in my code: https://codecov.io/gh/YaLTeR/plitki/src/master/plitki-core/src/state.rs#L307

**Comment by Diggsey** [comment] 2020-02-12 19:04
It seems like most literals/constants are missed:

![image](https://user-images.githubusercontent.com/451321/74367663-26541a80-4dca-11ea-91db-acf612f3cadf.png)

Also, I don't know if this is feasible, but it would be useful to disable coverage for panicking code blocks. At the moment all uses of `.expect()`, `.unwrap()`, etc. show up as uncovered, presumably because the panic branch is never hit.

**Comment by xd009642** [comment] 2020-02-15 19:44
There are some improvements to coverage in develop that catch some false negatives. Won't fix all the issues but it will help with a number of them.

I also might close this issue and the other missing coverage ones and make a pinned one

**Comment by xd009642** [comment] 2020-02-23 21:45
Closing in favour of https://github.com/xd009642/tarpaulin/issues/351

**Closed by xd009642** 2020-02-23 21:45 UTC
Labels: Instrumentation, enhancement, hacktoberfest
