### ISSUE TITLE
tarpaulin hangs after printing Code is mulithreaded, disabling hit count

### ISSUE THREAD

**Issue by messense** [xd009642/tarpaulin#80] opened 2018-01-21 06:55 UTC
https://travis-ci.org/messense/fasttext-rs/jobs/331384912

**Comment by xd009642** [comment] 2018-01-21 10:20
For now if you use the `--no-count` flag you won't experience this issue. This issue is a tricky one, I'll let you know when there's any progress!

**Comment by messense** [comment] 2018-01-21 14:15
It seems that `--no-count` doesn't work either.

https://travis-ci.org/messense/fasttext-rs/jobs/331417232

**Comment by bheisler** [comment] 2018-01-21 17:06
I'm seeing this issue as well:

https://travis-ci.org/japaric/criterion.rs/jobs/331479649

Will try adding `--no-count`.

**Comment by bheisler** [comment] 2018-01-21 17:25
Adding `--no-count` seemed to work for me. One of my trial builds skipped running some of the tests for some reason though, and it reported incorrect coverage numbers. That's probably unrelated, but I thought I should mention it.

**Comment by xd009642** [comment] 2018-01-21 17:36
If you check #63 to see if any of the inaccuracies are mentioned in the last comment. If not pop down a comment letting me know what they are if they're in the same vein, otherwise open a new issue :+1:

**Comment by bheisler** [comment] 2018-01-21 17:56
Nothing like that, it just skipped running one of the test executables. No idea why. I'll raise an issue if it happens again or I can get any more information than that.

**Comment by xd009642** [comment] 2018-01-21 18:04
Alright, I'll test my latest changes to tarpaulin on both your repos to ensure things are fixed. Also, the `--verbose` flag may help in diagnosing some issues if you see these things again.

**Comment by messense** [comment] 2018-01-24 14:42
Another hanging case but this time without the `Code is mulithreaded, disabling hit count` output.

https://travis-ci.org/messense/rust-jieba/jobs/332809662

Maybe it has something to do with interfacing with C/C++?

**Comment by xd009642** [comment] 2018-01-24 18:31
So I've tried both rust-jieba and fasttext on my own computer and tarpaulin runs fine. That wasn't on latest nightly though so I'm just updating and trying again. Also, with jieba it reported the coverage of the c++ source files as well!

**Comment by xd009642** [comment] 2018-01-24 18:45
Hang on I think I might have something. My example of a working travis starts with:

```
language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
```

While your travis file starts with:

```
sudo: required
language: rust
rust:
  - stable
  - nightly
cache: cargo
```

Try adding the missing dependency and use trusty. This may be caused by not all the dependencies for my dependent crates being satisfied!

**Comment by xd009642** [comment] 2018-01-24 20:13
I forked jieba and made the travis.yml changes advised and it works, closing this issue!

**Comment by messense** [comment] 2018-01-25 01:51
I am curious why the pre-compiled binary does not work on Travis CI.

**Comment by messense** [comment] 2018-01-25 02:39
rust-jieba works now but fasttext-rs does not work.

Change: https://github.com/messense/fasttext-rs/commit/282b9a69e6cc7d806745bfbb7f0efb1c36fcb4b6
Build: https://travis-ci.org/messense/fasttext-rs/jobs/333083875

**Comment by xd009642** [comment] 2018-01-27 18:34
So I've been playing around with this, and it seems I exclude the C/C++ code it works. You just need to install the latest tarpaulin from develop and use the new exclude-files flag. Below is the necessary command:

```
- cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch develop
- cargo tarpaulin --no-count --exclude-files *.h *.c*
```

You may have to clear your travis cache to ensure it doesn't use a cached different version of tarpaulin.

Now coverage of C/C++ works on my system, so I'm now wondering what the possible differences in environment are. I'll open an issue tagged as an enhancement to improve incidental coverage of code provided in other languages, but I'm happy this issue is now closed :+1:

**Closed by xd009642** 2018-01-27 18:34 UTC
Labels: bug

**Comment by messense** [comment] 2018-01-28 03:53
It works, thanks a lot!
