### ISSUE TITLE
Inlining functions results in one uncovered line

### ISSUE THREAD

**Issue by newpavlov** [xd009642/tarpaulin#79] opened 2018-01-17 10:20 UTC
For example this [line](https://github.com/RustCrypto/block-ciphers/blob/aesni_v0.2.0/aesni/src/aes128/expand.rs#L43) in `aesni` crate reported as uncovered one, while function body is counted as covered.

**Comment by xd009642** [comment] 2018-01-17 22:05
I can replicate this on my machine and have started looking into it, so I'll let you know when there are any updates.

**Comment by xd009642** [comment] 2018-04-17 21:14
Hi, I'm sorry I haven't looked at this sooner but is this still an issue? Looking at the link it looks like the code has changed a lot in the intervening time. I did do some work on inline coverage for some other issue maybe also as part of #63 so if you still have an instance of the issue let me know, I'll test with the latest development version and if it's fixed or a duplicate close the issue.

Sorry about taking so long to get back to you, been snowed under recently with work!

**Comment by newpavlov** [comment] 2018-04-18 09:47
On v0.5.6 this issue is still reproducible. You can switch to tag `aesni_v0.2.0` to test it. (I've edited the link)

BTW: It looks like tarpaulin does not pass `RUST_FLAGS` when compiling crates, in the new `aesni` version it requires to enable `aes` target feature.

**Comment by xd009642** [comment] 2018-04-18 18:35
That's odd looking at the code it looks like it imports rust flags and appends to it... That may be a change that came after 0.5.6, I'll look into it but if you fancy being on the cutting edge installing from the `develop` branch gives you my latest and greatest stable version ;)

**Comment by xd009642** [comment] 2018-04-19 17:51
Also, 0.5.6 isn't the latest/greatest you need to install from github and the `develop` branch for that! 

Going back to aesni was helpful though I realised `unsafe {` on it's own line was a false negative and have just fixed that! Also, `asm!` blocks are going to have to be considered and handled

**Comment by xd009642** [comment] 2018-05-15 21:50
Just tried this on the latest develop and latest nightly since I've changed a lot of things around and rustc has had some big changes and the line doesn't show up as a coverable line anymore and the body is all covered. This makes sense to me given it's inlined so there's no code executed to change context on function entry. Given it works I'm closing this issue :+1:

If you want to try it out, you can install latest develop via: `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch develop` the rustflag is due to a dependency on `syn` as `syntex_syntax` panics on some new rust syntax.

**Closed by xd009642** 2018-05-15 21:50 UTC
Labels: enhancement

**Comment by newpavlov** [comment] 2018-05-15 21:53
Great! Thanks!

**Comment by orium** [comment] 2019-03-10 19:37
@xd009642 It seems this bug is present again.

**Comment by xd009642** [comment] 2019-03-10 20:01
@orium could you post an example of the issue either in a project or a minimal reproducible example in https://github.com/xd009642/tarpaulin/issues/136

**Comment by orium** [comment] 2019-03-10 20:22
Done: https://github.com/xd009642/tarpaulin/issues/136#issuecomment-471340525
