### ISSUE TITLE
Doctests marked should_panic should not panic

### ISSUE THREAD

**Issue by cschwan** [xd009642/tarpaulin#493] opened 2020-07-06 07:14 UTC
It seems that panicking doctests marked as `should_panic` causes the tests run with `tarpaulin` to panic instead marking it a success.

This happens in my github action ([output](https://github.com/N3PDF/pineappl/runs/840371788), with Rust nightly and run with `--run-targets Tests,Doctests`),

    [INFO tarpaulin] running /home/runner/work/pineappl/pineappl/target/doctests/src_lumi_rs_36_0/rust_out
    thread 'main' panicked at 'assertion failed: !entry.is_empty()', pineappl/src/lumi.rs:43:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

for a [doctest](https://github.com/N3PDF/pineappl/blob/master/pineappl/src/lumi.rs#L36) which expects a panic in this situation and is marked as `should_panic`. Running with `RUST_BACKTRACE=1` shows that the test panics at [line 43](https://github.com/N3PDF/pineappl/blob/master/pineappl/src/lumi.rs#L43), as expected. When run with `cargo test` the test succeeds.

**Comment by xd009642** [comment] 2020-07-06 08:35
I was a bit thrown initially since I added should_panic handling for doc tests previously and it worked with my tests. But I think after looking at the test I see what it is! Your test is marked as `rust,should_panic` but I didn't take into account the markdown formatting so it might only work with `should_panic`

This should be a simple enough fix in `src/cargo.rs` I'll look into it when I'm finished at work :+1:

**Comment by cschwan** [comment] 2020-07-06 10:06
Thanks for looking into it! Removing `rust,` did not fix it, unfortunately; there must be something else. I also checked the following attributes, maybe that helps tracking down the problem:
- `ignore` and `rust,ignore` correctly ignore the test,
- but `compile_fail` and `rust,compile_fail` seem to work a bit differently; if the test doesn't compile, it doesn't appear with an `[INFO tarpaulin]` line (probably correct), but if the test does compile, it will be executed and the outcome will decide whether it's a fail or not (wrong). In this case compilation should mean fail.

**Comment by xd009642** [comment] 2020-07-06 10:09
hmm if you use `--debug` it should give some more useful information (but also a lot of cargo build output). I also wasn't aware of `compile_fail` tests in doctests I'll aim to add something for that

**Comment by cschwan** [comment] 2020-07-07 07:27
I didn't learn anything useful from adding `--debug`. But if you point me to where `should_panic` is handled in tarpaulin I could try to see where the problem is.

**Comment by xd009642** [comment] 2020-07-07 07:43
src/cargo.rs finds which doc tests should panic and in src/lib.rs the return codes are checked to make sure tests passed or panicked as expected

**Comment by xd009642** [comment] 2020-07-07 18:57
@cschwan ah I've figured out where the issue is. Doctest filenames are generated from the file path and line number. My doctest handling in `get_panic_handling` checks this relative to workspace root, but it's actually done relative to package root. Once I fix that it should analyse the files and find the should_panics

**Comment by xd009642** [comment] 2020-07-07 19:43
You can try out a patch I've done on branch issue_493

**Comment by cschwan** [comment] 2020-07-07 21:31
Great, that works and fixes the reported problem. Thanks a lot!

**Comment by xd009642** [comment] 2020-07-07 21:55
Great I'll endeavour to finish any polishing and get it into the develop branch tomorrow then. 

I'll probably have another release at the weekend as well just gonna see if I can fix a few more things easily before then and try it on a few more projects with doc tests just to be safe

**Closed** 2020-07-08 18:31 UTC
