### ISSUE TITLE
`nested import groups` is not supported

### ISSUE THREAD

**Issue by codeworm96** [xd009642/tarpaulin#112] opened 2018-05-25 16:14 UTC
`nested import groups` has landed in rust 1.25.0 stable.
We can write code like: `use std::{fs::File, io::Read, path::{Path, PathBuf}};`
However, when run `cargo tarpaulin --no-count --skip-clean --out Xml` on such code, got the following output:

```
Building project
Launching test
running /home/circleci/tikv/target/debug/deps/tikv-daafaa80d841e8d1
error: expected one of `,` or `as`, found `::`
   --> /home/circleci/tikv/src/config.rs:699:69
    |
699 |     use serde::{Deserialize, Deserializer, Serialize, Serializer, de::{Error, Unexpected}};
    |                                                                     ^^ expected one of `,` or `as` here

error: internal compiler error: Error constructed but not emitted

thread 'main' panicked at 'explicit panic', /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.59.1/src/diagnostic_builder.rs:204:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
   6: <syntex_errors::diagnostic_builder::DiagnosticBuilder<'a> as core::ops::drop::Drop>::drop
   7: cargo_tarpaulin::source_analysis::get_line_analysis
   8: cargo_tarpaulin::tracer::generate_tracer_data
   9: cargo_tarpaulin::get_test_coverage
  10: cargo_tarpaulin::launch_tarpaulin
  11: cargo_tarpaulin::run
  12: cargo_tarpaulin::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: <unknown>
```

**Comment by xd009642** [comment] 2018-05-25 16:22
This is supported in the latest develop branch, and will be in my upcoming release (coming soon). If you use docker you can install using `develop` and `develop-nightly` images or install with cargo like `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch develop` (the nested use failure is caused by syntex_syntax and syn adds a requirement to the rustflags to unlock the necessary features.)

I'll add a note to the README because a couple of people have raised this already

**Closed by xd009642** 2018-05-25 16:22 UTC
