### ISSUE TITLE
Not covering all files

### ISSUE THREAD

**Issue by Coding-Doctors** [xd009642/tarpaulin#64] opened 2017-11-19 16:12 UTC
https://codecov.io/gh/Coding-Doctors/sudobot-rs/src/ci/src only has one of the like 5 files that are used, better seen in the CI build where tarpaulin runs (verbose output)
https://travis-ci.org/Coding-Doctors/sudobot-rs/jobs/302635711
https://github.com/too-r/sudobot-rs/tree/master/src

**Comment by xd009642** [comment] 2017-11-19 18:40
So this seems a bit weird. This is what I got when I cloned your project and ran tarpaulin on it on my own machine:

```
Launching test
running /home/xd009642/code/rust/meta_tarpaulin/sudobot-rs/target/debug/deps/sudobot_rs-dc0dcb6f375221b1
Working dir /home/xd009642/code/rust/meta_tarpaulin/sudobot-rs/Cargo.toml

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Coverage Results
src/commands/mod.rs: 0/2
src/handlers/mod.rs: 0/11
src/handlers/moderation.rs: 0/20
src/main.rs: 0/21

0.00% coverage, 0/54 lines covered
Tarpaulin finished
```

Four out of five files but that may always be down to macro use. I'll try cloning your project and running it on travis myself to see if I can get to the bottom of it.

**Comment by xd009642** [comment] 2017-12-04 20:08
So this is down to #70 which is caused by rust-lang/rust#46467. So I'm hoping as this is a regression in the compiler once the issue is closed in the compiler you should see all the source files in coverage results. I'm going to close this issue because of that but you can follow developments in #70 or if you like I can tag you when it's closed.

**Closed by xd009642** 2017-12-04 20:08 UTC
Labels: bug
