### ISSUE TITLE
Tarpaulin sometimes detects multithreading in a single-threaded library crate

### ISSUE THREAD

**Issue by parasyte** [xd009642/tarpaulin#94] opened 2018-03-18 06:36 UTC
I don't know how to diagnose this, or even how to provide a sample that can reproduce it. I have a private crate that is by-design entirely single-threaded. When I run the tests though Tarpaulin in a `rustlang/rust:nightly` Docker container, I sometimes get the following warning after the first or second test completes:

```
Code is mulithreaded, disabling hit count
```

It doesn't change coverage results or anything, but it certainly is odd and surprising behavior.

Is there anything I can do to provide more information? Verbose logging, or sharing my `Cargo.lock`? Maybe one of my dependencies is doing something weird.

**Comment by xd009642** [comment] 2018-03-18 11:14
If you can't share the project, making a small project that recreates the issue would be most helpful. If you know which test(s) it happens in hopefully it will be easier to recreate. I don't think verbose logging will help, but maybe the `Cargo.lock`.

It might also be worth checking the newest version on the `develop` branch to see if it's still an issue. I haven't had a release yet this year so it may have been inadvertently fixed.

**Comment by parasyte** [comment] 2018-03-18 20:14
I'll give it a shot with the `develop` branch and let you know if it still occurs. It appears to happen in random tests, but I might also be able to cut it down to a minimal test case with some effort.

Here are the `Cargo.toml` and `Cargo.lock` files, maybe something stands out or seems vaguely suspicious.

```toml
#Cargo.toml
[package]
name = "odyssium"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]

[dependencies]
bitflags = "1.0.0"
cgmath = "0.15.0"
```

```toml
#Cargo.lock
[[package]]
name = "approx"
version = "0.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "bitflags"
version = "1.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "cgmath"
version = "0.15.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "approx 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "num-traits 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.3.22 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "fuchsia-zircon"
version = "0.3.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "bitflags 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "fuchsia-zircon-sys 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "fuchsia-zircon-sys"
version = "0.3.3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "libc"
version = "0.2.39"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "num-traits"
version = "0.1.43"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "num-traits 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "num-traits"
version = "0.2.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "odyssium"
version = "0.1.0"
dependencies = [
 "bitflags 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "cgmath 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rand"
version = "0.3.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "fuchsia-zircon 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.39 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rand"
version = "0.4.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "fuchsia-zircon 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.39 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "winapi"
version = "0.3.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "winapi-i686-pc-windows-gnu"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "winapi-x86_64-pc-windows-gnu"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
"checksum approx 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = "08abcc3b4e9339e33a3d0a5ed15d84a687350c05689d825e0f6655eef9e76a94"
"checksum bitflags 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = "b3c30d3802dfb7281680d6285f2ccdaa8c2d8fee41f93805dba5c4cf50dc23cf"
"checksum cgmath 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = "d2372c02a7cfabf871ec42ecc968406a7b5916bcfd51defc6a0498fcb19fa2e5"
"checksum fuchsia-zircon 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = "2e9763c69ebaae630ba35f74888db465e49e259ba1bc0eda7d06f4a067615d82"
"checksum fuchsia-zircon-sys 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = "3dcaa9ae7725d12cdb85b3ad99a434db70b468c09ded17e012d86b5c1010f7a7"
"checksum libc 0.2.39 (registry+https://github.com/rust-lang/crates.io-index)" = "f54263ad99207254cf58b5f701ecb432c717445ea2ee8af387334bdd1a03fdff"
"checksum num-traits 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)" = "92e5113e9fd4cc14ded8e499429f396a20f98c772a47cc8622a736e1ec843c31"
"checksum num-traits 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = "0b3c2bd9b9d21e48e956b763c9f37134dc62d9e95da6edb3f672cacb6caf3cd3"
"checksum rand 0.3.22 (registry+https://github.com/rust-lang/crates.io-index)" = "15a732abf9d20f0ad8eeb6f909bf6868722d9a06e1e50802b6a70351f40b4eb1"
"checksum rand 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = "eba5f8cb59cc50ed56be8880a5c7b496bfd9bd26394e176bc67884094145c2c5"
"checksum winapi 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = "04e3bd221fcbe8a271359c04f21a76db7d0c6028862d1bb5512d85e1e2eb5bb3"
"checksum winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6"
"checksum winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f"
```

**Comment by xd009642** [comment] 2018-03-18 22:24
I guess one of the dependencies uses threads internally. What's happening under the hood is that tarpaulin is counting the amount of threads that are created and destroyed to keep a track of how many active threads there are. It then warns you if there are multiple threads to let you know it's forcing the `--no-count` option on you. (Some coverage reports use hit-rate as a metric which relies on the hits being counted).

The reason for this is that tarpaulin uses the ptrace API to trace the test execution. You have the program being executed and line instructions are overwritten with the breakpoint opcode and restored when it's hit. 

The ptrace continue and step commands cause all threads to continue so you basically end up with a race condition where the program is global mutable state being altered and each thread may change it so you can get a deadlock of sorts. This can cause the program to get stuck on a single instruction or even segfault which is why this happens.

This is kind of a duplicate of #35 so I'm tempted to close it, but I'll leave this open for discussion etc and in case any new insights arise.

**Comment by parasyte** [comment] 2018-03-19 01:07
That makes sense. `cgmath` uses `rand` for implementing things like constructing random angles. I don't actually use any of the random APIs, directly. But `rand` has a method of retrieving randomness from the OS, and it uses threads to do so.

I guess you don't have a deterministic way to count threads, and that would explain why I only see the warning intermittently? The thread counter would only trigger if it happens to fall within the short time that `rand` is seeding the PRNG... Just a guess.

**Comment by xd009642** [comment] 2018-03-19 18:08
It is slightly deterministic in that it's based on the ptrace events, but with multiple events firing off at once at no guarantee on the order they'll be handled it's possible for the thread count to be incremented and decremented before a `SIGSTOP`. 

Well as we've got to the bottom of this and it's covered by #35 I'm going to close this issue! If the message bothers you, or you don't care about hit-rate and you want tarpaulin to run faster `--no-count` will sort you out :+1:

**Closed by xd009642** 2018-03-19 18:08 UTC
Labels: enhancement

**Comment by parasyte** [comment] 2018-03-20 16:04
No problem! Just to followup, I used the arg as you suggested, and saw much faster test results. 💟
