### ISSUE TITLE
Failed to get test coverage! Error: missing section: CoverageFunctions

### ISSUE THREAD

**Issue by robatipoor** [xd009642/tarpaulin#1465] opened 2024-01-29 10:49 UTC
Cargo tarpaulin failed during the execution of the "check coverage" command line tests. You can review the error details in the GitHub Actions link below:

[GitHub Actions - Test Coverage Job](https://github.com/robatipoor/pf/actions/runs/8861266670/job/24333129286#step:7:867)

The Cargo tarpaulin configuration can be found at the following link:

[Cargo Tarpaulin Configuration](https://github.com/robatipoor/pf/blob/coverage-test-problem/.github/workflows/test-coverage.yml#L45)

For your reference, an example of the command line test is available here:

[Command Line Test Example](https://github.com/robatipoor/pf/blob/coverage-test-problem/cli/tests/cli/ping_cli_test.rs#L7)

Thank you for your attention.

**Comment by Sajjon** [comment] 2024-02-17 13:08
I got this too in Sargon: https://github.com/radixdlt/sargon
Never had an issue until some days ago, hmm...

**Comment by xd009642** [comment] 2024-04-27 09:26
So this may have been fixed in the latest release, can you confirm if it's still an issue or not?

**Comment by robatipoor** [comment] 2024-04-28 06:47
After cleaning the GitHub Action caches and rerunning the pipeline, I received the same error message: "Error: missing section: CoverageFunctions."

**Comment by xd009642** [comment] 2024-04-28 12:35
Okay I've realised what the issue is (particularly for pf but sargon is likely the same thing). In pf pf-api and pf-cli are built separately and lack the llvm coverage instrumentation. I'm going to look into how they're built for the tests as maybe tarpaulin should be propagation some rustflags etc in a way that could solve this

**Comment by xd009642** [comment] 2024-04-28 14:27
Okay I have a PR, you can install it and try it out like:

```
cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch fix/missing-coverage-functions
```

I've tested it on pf and it works as expected (and now we also get coverage for the spawned CLI app!) I'll run it through a few more tests probably tomorrow and make sure it doesn't break anything existing.

**Comment by robatipoor** [comment] 2024-04-28 17:46
Yes, the problem is solved. Thank you.

**Comment by xd009642** [comment] 2024-04-29 08:18
Nice merged in, this'll be in the next release (should be later this week just looking at one other issue beforehand)

**Closed by xd009642** 2024-04-29 08:18 UTC
Labels: bug
