### ISSUE TITLE
unable to generate coverage info with cc-rs

### ISSUE THREAD

**Issue by calidion** [xd009642/tarpaulin#280] opened 2019-10-30 06:36 UTC
you can check code here:

`https://github.com/cryptonote-rust/raw-crypto`

**Comment by xd009642** [comment] 2019-11-02 21:35
I don't know if this was caused by the issue that was fixed in the 0.9.1 release but I can't recreate this.

This is my output

```
[xd009642@localhost raw-crypto]$ cargo tarpaulin
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/xd009642/code/rust/metatarp/raw-crypto/target/debug/deps/cryptonote_raw_crypto-565304497bc58c83

running 11 tests
...........
test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| ext/crypto/aesb.c: 0/21
|| ext/crypto/blake256.c: 93/187
|| ext/crypto/chacha.c: 107/114
|| ext/crypto/crypto-ops.c: 2043/2637
|| ext/crypto/crypto.c: 188/251
|| ext/crypto/groestl.c: 146/165
|| ext/crypto/hash-extra-blake.c: 3/3
|| ext/crypto/hash-extra-groestl.c: 3/3
|| ext/crypto/hash-extra-jh.c: 4/4
|| ext/crypto/hash-extra-skein.c: 4/4
|| ext/crypto/hash-ops.h: 0/3
|| ext/crypto/hash.c: 10/10
|| ext/crypto/jh.c: 85/116
|| ext/crypto/keccak.c: 44/87
|| ext/crypto/oaes_lib.c: 0/564
|| ext/crypto/random.c: 31/47
|| ext/crypto/skein.c: 106/347
|| ext/crypto/slow-hash.c: 151/188
|| ext/crypto/tree-hash.c: 0/26
|| ext/crypto/util.h: 30/30
|| ext/cryptonote/core/difficulty.cpp: 51/56
|| ext/util/vec_pub.cpp: 21/21
|| ext/util/vec_signature.cpp: 18/18
|| src/chacha.rs: 33/33
|| src/hash.rs: 66/67
|| src/key.rs: 66/66
|| src/lib.rs: 57/59
|| src/ring.rs: 31/32
|| src/scalar.rs: 198/201
|| 
66.96% coverage, 3589/5360 lines covered
```

If you can confirm it works for you now with the latest release or let me know if it still doesn't work and I can help you get to the bottom of it

**Comment by calidion** [comment] 2019-11-03 06:38
```
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/eric/cryptonote-rust/raw-crypto/target/debug/deps/cryptonote_raw_crypto-a742a6b73723a467

running 11 tests
.Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"
```
upgraded to 0.9.1
still not working

**Comment by xd009642** [comment] 2019-11-03 15:02
Does it always not work or only sometimes? I'd do 1000 runs and see what failure rate I get

**Comment by calidion** [comment] 2019-11-03 15:51
always fail.

**Comment by xd009642** [comment] 2019-11-03 17:01
Well on my machine it only failed 37% of the time, either way I can reproduce it so I can investigate it.

**Comment by xd009642** [comment] 2019-11-04 22:37
So the segfault is caused by this `assert(curstate == 1);` expression in the finalizer in random.c - `ext/crypto/random.c:106` and from a handful of samples this is what always causes the issue.

Given this is a thread safety issue judging from the code comments it might be you want to run with `--test-threads 1` as a argument forwarded to the test or alternatively with the `--release` flag to build raw-crypto as a release binary with debug symbols and also disabling the assert (educated guess I'm still testing this one).

What would be better is figuring out what threading issue is being caused. From the logs I get a SIGTRAP from the test PID and an exit event from the child thread it spawned to run the test (in that order). I then continue the test PID for the stop and detach the tracing of the thread as it's exited. Then the assert triggers next and I get a SIGABRT.

If you have any insights into how `deinit_random` can be called while `generate_random_bytes_not_thread_safe` is being executed it would be appreciated.  There is a chance there's an issue in your tests and how rustc uses threads which tarpaulin is amplifying

**Comment by calidion** [comment] 2019-11-05 05:49
it seems 

```
--test-threads 1
```
is not a valid parameter.

both `cargo tarpaulin --test-threads 1` and `cargo test --test-threads 1` does not work.

```
error: Found argument '--test-threads' which wasn't expected, or isn't valid in this context

USAGE:
    cargo tarpaulin [FLAGS] [OPTIONS] [-- <args>...]

For more information try --help
```

```
 cargo test --test-threads 1
error: Found argument '--test-threads' which wasn't expected, or isn't valid in this context
	Did you mean --test?

USAGE:
    cargo test --test <NAME>...

For more information try --help
```

And `cargo test` works for  the project without ` --test-threads 1`

**Comment by xd009642** [comment] 2019-11-05 07:11
They're forwarded to the underlying binary so you need a `--` first like `-- --test-threads 1`

**Comment by calidion** [comment] 2019-11-05 07:48
still not working:

```
> cargo test -- --test-threads 1
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running target/debug/deps/cryptonote_raw_crypto-f42274897db40f86

running 11 tests
test chacha::tests::should_generate_key_and_cipher_contents ... ok
test hash::tests::should_check_hash_with_difficulty ... ok
test hash::tests::should_get_fast_hash ... ok
test hash::tests::should_test_fast ... ok
test hash::tests::should_test_slow ... ok
test hash::tests::should_test_slow_hash ... ok
test key::tests::should_get_public_key_from_generated_secret_key ... ok
test key::tests::should_get_public_key_from_secret_key ... ok
test scalar::tests::should_test_scalar ... ok
test scalar::tests::should_to_hash ... ok
test tests::should_test_difficulty ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests cryptonote-raw-crypto

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

> cargo tarpaulin
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/eric/cryptonote-rust/raw-crypto/target/debug/deps/cryptonote_raw_crypto-a742a6b73723a467

running 11 tests
.Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"
```

**Comment by calidion** [comment] 2019-11-05 07:50
```
cargo tarpaulin -- --test-threads 1
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/eric/cryptonote-rust/raw-crypto/target/debug/deps/cryptonote_raw_crypto-a742a6b73723a467

running 11 tests
Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"

```

**Comment by xd009642** [comment] 2019-11-05 08:01
Try `--release` on tarpaulin that's what I was most confident with. Also if that fails run with the `--debug` flag as well (tarpaulin debug printouts) and send that output

**Comment by calidion** [comment] 2019-11-05 08:31
thanks.  It is ok now.

```
cargo tarpaulin --release
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/eric/cryptonote-rust/raw-crypto/target/release/deps/cryptonote_raw_crypto-ec80d8177cd86b66

running 11 tests
...........
test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/chacha.rs: 33/33
|| src/hash.rs: 66/67
|| src/key.rs: 66/66
|| src/lib.rs: 57/59
|| src/ring.rs: 37/38
|| src/scalar.rs: 198/198
|| 
99.13% coverage, 457/461 lines covered
```

**Closed** 2019-11-05 10:32 UTC
Labels: bug
