### ISSUE TITLE
Nightly cargo changes can break tarpaulin compilation (remove cargo dep)

### ISSUE THREAD

**Issue by Razican** [xd009642/tarpaulin#339] opened 2020-02-05 20:10 UTC
I'm getting an error when using `cargo tarpaulin` in the [Rocket][rocket] repository on the `async` branch. It turns out that they removed the `extern crate proc_macro;` from the `./contrib/codegen/` crate, which gave a warning in Rust 2018, since it's considered non-idiomatic.

It compiles fine with `cargo build` or `cargo test`, but it gives the following error when running the latest `cargo tarpaulin`:

```
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
error[E0432]: unresolved import `proc_macro`
  --> contrib/codegen/src/lib.rs:39:5
   |
39 | use proc_macro::TokenStream;
   |     ^^^^^^^^^^ help: a similar path exists: `quote::proc_macro`

error[E0432]: unresolved import `proc_macro`
 --> contrib/codegen/src/database.rs:1:5
  |
1 | use proc_macro::TokenStream;
  |     ^^^^^^^^^^ help: a similar path exists: `quote::proc_macro`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rocket_contrib_codegen`.
Error: "Failed to compile tests! Error: build failed"
```

If you give me some pointers I can try to fix it :)

[rocket]: https://github.com/SergioBenitez/Rocket/tree/async

**Comment by xd009642** [comment] 2020-03-04 22:32
I think this might be because `proc-macro=true` in a `Cargo.toml` allows certain extra nightly proc-macro features. I've had a brief look over the cargo source but can't find anything obvious I should be doing so raised this issue https://github.com/rust-lang/cargo/issues/7968 

In the meantime I'll continue to look but it seems to be a cargo usage based issue

**Comment by xd009642** [comment] 2020-03-04 22:56
So I moved my cargo dependency to the latest on master and it seems to solve the issue. You can try it out by installing from https://github.com/xd009642/tarpaulin/tree/issue_339

**Comment by xd009642** [comment] 2020-03-05 08:27
So over this weekend I'm going to follow some advice of a cargo maintainer and move to using https://docs.rs/cargo_metadata/ to handle my interactions with cargo as this will keep tarpaulin more up-to-date with nightly features and stop issues like this in future. I'll close this issue when that's done, confirmed to work and released :smile:

**Comment by Razican** [comment] 2020-03-05 08:30
This sounds great! Thanks for your work :) It really sounds promising, to be able to use the same binary that `cargo test` is using. It should also reduce tarpaulin compile times by removing the `cargo` dependency :)

**Comment by Razican** [comment] 2020-03-09 19:21
Let me know if I can help with this!

**Comment by xd009642** [comment] 2020-03-09 23:18
So far I've mostly got it down, just two more tests need move from red to green (and that's ignoring nightly only tests)

**Comment by xd009642** [comment] 2020-03-14 09:51
This should be fixed in the 0.11.1 release since cargo was updated. I'm still working on removing cargo as a dependency though so I'll keep this issue open to track that (and slightly rename it)

**Comment by Razican** [comment] 2020-04-02 07:34
Hi, so this particular issue is solved, cool!

How is the cargo dependency removal going?

**Comment by xd009642** [comment] 2020-04-02 09:27
There's a version without cargo as a dependency on the develop branch if you want to try it. It works exactly the same on all the projects I've tested with but could do with more testing!

**Comment by xd009642** [comment] 2020-04-07 20:13
This version is now released although it looks like there might be a regression with examples which is handled by another issue. So I'm going to close this

**Closed by xd009642** 2020-04-07 20:13 UTC

**Comment by Razican** [comment] 2020-04-09 15:56
Great, thanks! Sorry I didn't have the time to check it.
