### ISSUE TITLE
`should_panic` marker not honored in README.md doctest

### ISSUE THREAD

**Issue by nu11ptr** [xd009642/tarpaulin#991] opened 2022-04-16 14:32 UTC
When using a doctest in a README.md file marked with `should_panic`, tarpaulin executes it but does not seem to parse out the `should_panic` as it ends in failure. Removing the `should_panic` flag (and removing the failing assert) and it passes as expected.

My repo is very small so can probably be used as a reproducible sample:

README:
https://github.com/nu11ptr/assert_unordered/blame/master/README.md#L25

Code that triggers README test:
https://github.com/nu11ptr/assert_unordered/blob/master/src/lib.rs#L40

I was expecting (or at least hoping) the test would pass like it does when executed with `cargo test`

**Comment by xd009642** [comment] 2022-04-16 14:52
This looks like a duplicate of https://github.com/xd009642/tarpaulin/issues/924 and this comment explains what is happening https://github.com/xd009642/tarpaulin/issues/924#issuecomment-1005258371  aside from better upstream support in rustc or the attribute finding code expanding preprocessor includes of text the only approach I could think of would be a hacky flag like `--doctests-always-pass`

**Comment by nu11ptr** [comment] 2022-04-16 19:25
Appreciate the fast response. Other than disabling my README test, any ideas for how to get tarpaulin to just _skip_ this test, but not cargo test? Otherwise I'll probably just have to disable the README test for now, thx.

**Comment by xd009642** [comment] 2022-04-16 19:32
There's the ignore attribute on doc tests, as described in the doctest [docs](https://doc.rust-lang.org/rustdoc/documentation-tests.html). Other than that not running tarpaulin for doc tests

**Comment by xd009642** [comment] 2023-01-26 21:15
Going to close this as duplicated, I also don't see myself supporting the include macros for doc tests in the near future (unfortunately)

**Closed by xd009642** 2023-01-26 21:15 UTC
