### ISSUE TITLE
cobertura xml line rate differs from the reported coverage in the console output

### ISSUE THREAD

**Issue by flaminggoat** [xd009642/tarpaulin#872] opened 2021-11-04 22:21 UTC
**Describe the bug**
cobertura xml line rate differs from the reported coverage in the console output. I though perhaps this is because it is including the coverage for  the examples folder. I have tried running with `cargo tarpaulin --out Xml --exclude-files examples/*` as suggested in #332 but this does not change anything.
```
|| Tested/Total Lines:
|| src/lib.rs: 5/11 +0.00%
|| src/reciever.rs: 71/87 +0.00%
|| src/sender.rs: 70/96 +0.00%
|| src/std_file_access.rs: 12/23 +0.00%
|| 
72.81% coverage, 158/217 lines covered, +0% change in coverage
```
```
<?xml version="1.0"?>
<coverage lines-covered="158" lines-valid="217" line-rate="0.3640552995391705" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0" version="1.9" timestamp="1636063732">
    <sources>
        <source>/home/a/source/sync-ftp</source>
    </sources>
    <packages>
        <package name="examples" line-rate="0" branch-rate="0" complexity="0">
            <classes></classes>
        </package>
```
Running with 

**To Reproduce**
If possible provide a minimal  example or project where you've observed the issue. Describe how you called tarpaulin and if it seems helpful provide a copy of what tarpaulin printed out to you.

**Expected behavior**

**Comment by xd009642** [comment] 2021-11-04 22:45
Ah I think I've found the cause of this, for the report it's actually calculating the average line rate. Let me work on a fix for this, and as you've found two issues tonight I figure it will be best if you just test the version I get and see if anything else stands out :sweat_smile:

**Comment by xd009642** [comment] 2021-11-04 23:11
If you check branch issue/872 it implements the fix for this. So if you install via that and make sure everything else is okay then I can patch anything else similarly simple :smile:

**Comment by flaminggoat** [comment] 2021-11-05 10:03
I think that fix gives the expected output  :+1: `cargo tarpaulin --out Xml`
```
<?xml version="1.0"?>
<coverage lines-covered="158" lines-valid="217" line-rate="0.728110599078341" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0" version="1.9" timestamp="1636105927">
    <sources>
        <source>/home/theo/source/sync-ftp</source>
    </sources>
    <packages>
        <package name="examples" line-rate="0" branch-rate="0" complexity="0">
            <classes></classes>
        </package>
        <package name="src" line-rate="0.728110599078341" branch-rate="0" complexity="0">
            <classes>
                <class name="lib" filename="src/lib.rs" line-rate="0.45454545454545453" branch-rate="0" complexity="0">
                    <methods />
                    <lines>
                        <line number="31" hits="0" />
 ```
 
```
|| Tested/Total Lines:
|| src/lib.rs: 5/11 +0.00%
|| src/reciever.rs: 71/87 +0.00%
|| src/sender.rs: 70/96 +0.00%
|| src/std_file_access.rs: 12/23 +0.00%
|| 
72.81% coverage, 158/217 lines covered, +0% change in coverage
```

**Comment by xd009642** [comment] 2021-11-05 10:08
Cool, I'll also write some tests for it tonight and then do another patch release

**Closed** 2021-11-05 22:04 UTC
