### ISSUE TITLE
Inconsistent segfault error (non-deterministic)

### ISSUE THREAD

**Issue by woshilapin** [xd009642/tarpaulin#461] opened 2020-05-28 17:40 UTC
On a project I'm working on, I have this inconsistent error

```
[ERROR tarpaulin] Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests
Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"
##[error]The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 1
```

I say _inconsistent_ because it never happens at the same time of the process.  I've been able to reproduce locally at some point but then, launching the same `cargo tarpaulin` command over and over, it eventually works. Funnier, it seems that once it works, it always works (I even was able to do a `cargo clean` and make it work). So the error never happen consistently.

I'm working on Ubuntu 20.04 with the following (but this error also happened on our CI https://github.com/CanalTP/transit_model/pull/558/checks?check_run_id=716136628)
```
$> rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
$> cargo --version
cargo 1.43.0 (2cbe9048e 2020-05-03)
$> rustc --version
rustc 1.43.1 (8d69840ab 2020-05-04)
$> cargo tarpaulin --version
cargo-tarpaulin version: 0.13.2
```

I looked for similar issues but didn't feel like the problem was the same. Sorry if this is a duplicate.

**Comment by Enrico2** [comment] 2020-05-29 22:15
Seeing the same problem, e.g. here https://github.com/apollographql/apollo-cli/pull/52/checks?check_run_id=721906925

**Comment by xd009642** [comment] 2020-05-29 22:42
Interesting, once I finish the stuff I'm currently working on I'll have a look and see if I can get to the bottom of it

**Comment by woshilapin** [comment] 2020-06-01 07:11
> Interesting, once I finish the stuff I'm currently working on I'll have a look and see if I can get to the bottom of it

Thank you very much, don't hesitate to ask if you need help, information or if I can do anything to help.  I'll try to do as much as possible.

**Comment by woshilapin** [comment] 2020-06-27 11:38
Hi, any news on this issue? Is there anything I can do to help?

**Comment by xd009642** [comment] 2020-06-27 12:16
I managed to recreate it once but haven't yet figured out what causes it. Though I admit I ended up not working on tarpaulin as much the past few weeks. I'll have a look today or tomorrow see if I can figure it out. 

I also made a tarpaulin debugging tool last year which I think I'll integrate into the code to make diagnosing issues like this easier. Right now it exists in a different repo as a harness around some of the internals and needs some updating. Once I've done that I might ask you if you can use that branch to generate some debug traces and send them to me

**Comment by xd009642** [comment] 2020-06-30 20:59
So I haven't managed to recreate it with transit_model with the latest tarpaulin, but also the traces that come out are so large I can't render them at a size where they're readable. Just trying to with apollo-cli. But @woshilapin and @Enrico2 do you still see this with the latest version or both the rust compiler (stable or beyond) and tarpaulin?

**Comment by zeeshanlakhani** [comment] 2020-07-03 19:50
Seeing the same issue: https://github.com/capsule-rs/capsule/pull/106/checks?check_run_id=835393227. Using nightly and the args below. 

```

Run actions-rs/cargo@v1
  with:
    command: tarpaulin
    args: -p capsule -l --count --exclude-files examples/* ffi/* macros/* --out Xml -Zpackage-features --features full
    use-cross: false
```

**Comment by xd009642** [comment] 2020-07-04 16:00
ahh capsule is good, I can recreate it reliably using it and there's no so many traces that it's insurmountable to display a plot :+1: I'll start using that to investigate this issue

**Comment by woshilapin** [comment] 2020-07-07 10:03
> So I haven't managed to recreate it with transit_model with the latest tarpaulin, but also the traces that come out are so large I can't render them at a size where they're readable. Just trying to with apollo-cli. But @woshilapin and @Enrico2 do you still see this with the latest version or both the rust compiler (stable or beyond) and tarpaulin?

Hi, sorry for not answering earlier. I tried again to run the build a few minutes ago and I'm still seeing the same error (you can check the build https://github.com/CanalTP/transit_model/pull/558/checks?check_run_id=845031615).

**Comment by woshilapin** [comment] 2020-09-02 13:33
I tried again today with version `0.14.3` (the last try was on `0.14.1`) but reached a different error than the original one in the ticket. Interestingly, I was using `actions-rs/rust-tarpaulin` to run `tarpaulin`. But then I tried to remove entirely `actions-rs/rust-tarpaulin` and install/run manually `tarpaulin`: it works!

So it might be the case that the bug has been fixed in the latest version? I'm curious if @zeeshanlakhani or @Enrico2 are still seing the problem on their sides?

**Comment by zeeshanlakhani** [comment] 2020-09-02 13:36
@woshilapin it didn't work for me on `0.14.2`, but I will try this later today with the recent version.

**Comment by xd009642** [comment] 2020-09-02 13:40
In the latest version I found that some linker settings cause cause dwarf lines marked at address 0x00 (+ offset) which I'd never seen before and caused a segfault. I added something to get the address range of the text section and not try to instrument addresses outside of it. 

I wouldn't think that would affect this as the segfault happened as soon as tarpaulin tried to place the breakpoint and happened every time... But then again linkers are part engineering, part black magic so maybe?

**Comment by zeeshanlakhani** [comment] 2020-09-02 15:47
@xd009642 @woshilapin still failing for me on `0.14.3`:

```
[ERROR tarpaulin] Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests
Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"
```

**Comment by Enrico2** [comment] 2020-09-05 17:23
Our code base changed significantly so it's possible that any attempt to
reproduce will not be reproducing under the same conditions. We are
currently using grcov (because it's also runnable on a Mac, for local
development), but I'm actually curious to try tarpaulin again to see if
there are changes in the coverage report. I will update once I do. Thanks!

**Comment by xd009642** [comment] 2020-11-11 00:11
tarpaulin once again has refined some of the tracing and offset handling and now adds less linker flags when building your tests. I haven't tried on capsule again but it's solved a number of different issues so :crossed_fingers:

**Comment by zeeshanlakhani** [comment] 2020-11-14 19:13
@xd009642 sadly:

```Nov 14 19:11:17.023  WARN cargo_tarpaulin::statemachine::linux: Failed to find process for pid: 10764
Nov 14 19:11:17.023  WARN cargo_tarpaulin::statemachine::linux: Failed to find traces for pid: 10764
Nov 14 19:11:17.024  WARN cargo_tarpaulin::statemachine::linux: Failed to find process for pid: 10764
Nov 14 19:11:17.024  WARN cargo_tarpaulin::statemachine::linux: Failed to find traces for pid: 10764
Nov 14 19:11:17.029 ERROR cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: Error running test - SIGILL raised in 10764
Error: "Failed to get test coverage! Error: Failed to run tests: Error running test - SIGILL raised in 10764"```

**Comment by bitshifter** [comment] 2021-01-02 10:33
I have been moving my code coverage from travis-ci to github actions and started to hit this issue. I switched from using the docker image to running `cargo install cargo-tarpaulin` before running coverage and the problem went away.

**Comment by xd009642** [comment] 2021-01-02 12:13
@bitshifter that might be down to the latest release being yanked but I haven't done anything to try and yank/replace the latest tag on docker hub. I'll try and do that today to fix the docker image

**Comment by robinst** [comment] 2021-01-05 04:27
For anyone else hitting the problem, you can pin the Docker image version in GitHub actions to 0.16.0 like this:

    container:
      image: xd009642/tarpaulin:0.16.0
      options: --security-opt seccomp=unconfined

**Comment by floric** [comment] 2021-02-22 15:45
Unfortunately I still experienced this bug with both versions (0.18 alpha as well as 0.16). I even didn't specify the number of concurrent runs to 1.

https://gitlab.com/floric/neuland/-/jobs/1047188715

```test db::change_listener::tests::should_listen_to_game_changes ... Feb 22 15:39:37.961 ERROR cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests
Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"```

**Comment by zeeshanlakhani** [comment] 2021-02-22 15:47
Oddly enough, on the newest rust and the latest tarpaulin version, we now don't get a segfault haha, e.g. https://github.com/capsule-rs/capsule/runs/1872983169.

**Comment by floric** [comment] 2021-02-22 15:49
haha :D Ok, I can try some more versions later.

**Comment by xd009642** [comment] 2021-02-22 15:59
@floric I tried your project a few times and it worked. How often does it fail? I'm on rust 1.50

```
|| Tested/Total Lines:
|| src/bin.rs: 0/2
|| src/db/change_listener.rs: 44/46
|| src/db/client.rs: 148/177
|| src/db/database.rs: 75/89
|| src/db/mod.rs: 0/8
|| src/jobs/cleanup_games.rs: 51/59
|| src/jobs/cleanup_players.rs: 50/66
|| src/jobs/mod.rs: 0/12
|| src/lib.rs: 0/9
|| src/model/card.rs: 2/15
|| src/model/game.rs: 89/113
|| src/model/player.rs: 67/77
|| src/model/proto/card.rs: 0/120
|| src/model/proto/game.rs: 48/249
|| src/model/proto/message.rs: 90/1299
|| src/model/proto/player.rs: 31/351
|| src/model/proto/task.rs: 0/160
|| src/model/task.rs: 0/9
|| src/server/app_context.rs: 36/41
|| src/server/auth.rs: 47/47
|| src/server/endpoints/active_game.rs: 0/68
|| src/server/endpoints/client_messages/auth_confirmed.rs: 68/86
|| src/server/endpoints/client_messages/game_started.rs: 77/79
|| src/server/endpoints/client_messages/name_updated.rs: 27/29
|| src/server/endpoints/games.rs: 127/135
|| src/server/logger.rs: 12/13
|| src/server/mod.rs: 0/36
|| src/server/reply.rs: 11/19
|| src/server/ws/client.rs: 12/59
|| src/server/ws/connections.rs: 34/69
|| 
32.35% coverage, 1146/3542 lines covered
```

**Comment by floric** [comment] 2021-02-23 07:20
In the GitLab CI it fails all the time, but with different end times. Sometimes I can see more test outputs, sometimes less.
One important note: I migrated from GitHub to Gitlab recently. In GitHub I used `actions-rs/tarpaulin@v0.1` with version 0.16, which worked flawlessly and stable. So it somehow needs to depend on the environment. For Gitlab I used this minimal Dockerfile for the CI environment:

```
FROM rust:1.50-slim as be-builder
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev
RUN cargo install cargo-tarpaulin && \
    cargo install gitlab_clippy && \
    cargo install cargo-audit && \
    rustup component add clippy
```

So it seems like it's somehow connected to this difference.

I don't want to waste your time in case it's about my config. I will compare the Github action code with my Dockerfile to see if there is any important difference. But thanks for checking my code! Tarpaulin is great work! :)

**Comment by xd009642** [comment] 2021-02-23 08:01
Might be worth refreshing the docker cache I didn't realise until recently the yanked 0.17 was still the latest image in docker. It's not replaced with 0.18.0-alpha1. Also docker needs different seccomp privileges which are detailed in the README. Hopefully it's one of those two issues :grin:

**Comment by xd009642** [comment] 2021-12-13 10:43
I'm just going to close this as it looks like we might have found the solution, but if it still doesn't work for you feel free to reopen or raise a new issue!

**Closed by xd009642** 2021-12-13 10:43 UTC
