### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by PSeitz** [xd009642/tarpaulin#155] opened 2018-10-09 06:21 UTC
Hi,

I get an eror, when trying to run tarpaulin on my project (https://github.com/PSeitz/veloci): "Error during run". A normal `cargo test` works fine.

Can I somehow enable more information on the error to see what's the cause?

**Comment by xd009642** [comment] 2018-10-09 06:31
There's the verbose flag which should print out some more information (or no more if the error is very early on) `cargo tarpaulin --verbose`.

**Comment by xd009642** [comment] 2018-10-09 06:57
Just got it you need `cargo-features = ["edition"]` at the top of your `Cargo.toml`. I'll add something so these early on cargo issues don't just fail without a message

**Comment by PSeitz** [comment] 2018-10-09 07:32
Thanks for the quick reply, I removed the `cargo-features = ["edition"]`, because it is no longer needed:

warning: the cargo feature `edition` is now stable and is no longer necessary to be listed in the manifest

**Comment by xd009642** [comment] 2018-10-09 17:19
So I'm using the latest release of cargo to crates.io to build the projects and handle the workspaces and features etc. So I would expect it to work the same as cargo does. So yeah no idea why it still needs it, I'll have a look in the cargo source and see if anything sticks out and improve the error messages for `Cargo.toml` related issues in the meantime.

**Comment by xd009642** [comment] 2018-10-09 20:55
Also I think edition isn't stable? I just did `rustup update stable` to be sure and it still required the cargo-features at the top for building with stable, but not when I built with nightly. Are you sure your default toolchain isn't nightly?

**Comment by PSeitz** [comment] 2018-10-09 21:53
Yes, I thought this was required, since it's mentioned in the docs `...tarpaulin is now a nightly only crate`

**Comment by xd009642** [comment] 2018-10-09 22:04
Oh I just meant regarding the edition being stable just cause I don't get that warning on stable.

Either way I've added an error message for cargo related issues, it's in the develop branch if you want to switch to that version and I'm gonna close this issue. I'm sure edition things will pop up as they move further towards becoming actually stable so issues can be raised as and when they're needed

**Closed by xd009642** 2018-10-09 22:04 UTC

**Comment by marcelbuesing** [comment] 2018-10-12 15:21
For anyone else running into the following error with version 0.6.8 it's caused by your dependency missing the `cargo-features = ["edition"]` in the Cargo.toml.

```
cargo tarpaulin -v
Running Tarpaulin
Cleaning project
Building project
Error: failed to compile: failed to load source for a dependency on `crate-xyz`
Error during run
```
