### ISSUE TITLE
Use Tarpaulin for Tarpaulin?

### ISSUE THREAD

**Issue by rask** [xd009642/tarpaulin#149] opened 2018-09-19 19:27 UTC
Would be neat seeing Tarpaulin gather code coverage on itself in Travis. Or are there any obstacles in "testing the tester"? Not sure how binary-level coverage testing works.

Let me know if this is a no can do. Let me know if you want help with this in some way.

**Comment by xd009642** [comment] 2018-09-19 19:49
So this is essentially a duplicate of #44. Currently, I can run tarpaulin on all my unit tests but the integration tests don't work. That's because when the test runs, tarpaulin is running a test binary that is running tarpaulin running a test binary. One of these tarpaulin instances steals signals meant for the other, or maybe they just get lost.

If #44 was sorted tarpaulin would be able to tarpaulin itself. It is something I'd appreciate help on because I've seen no evidence of this use case covered in the ptrace documentation.

But yeah if you want to move any discussion to #44 I'll close this as a duplicate :+1:

**Closed by xd009642** 2018-09-19 19:49 UTC
Labels: duplicate

**Comment by rask** [comment] 2018-09-19 21:06
Missed the previous issue. Sorry for making noise. :)
