### ISSUE TITLE
[Windows] Tarpaulin creates lcov.info in the wrong folder

### ISSUE THREAD

**Issue by dkudlek** [xd009642/tarpaulin#1147] opened 2022-11-27 13:38 UTC
# Describe the bug
When tarpaulin writes lcov.info it gets the wrong current directory. It writes the file into an subfolder instead of the root folder. Specifying `--root` or `--output-dir` did not help.

# To Reproduce
Project structure:  [challenge-rust](https://github.com/dkudlek/challenge-rust)
```
root/Cargo.toml
root/explore_dungeon
root/find_unique_interval
root/level_buildings
root/start_chain_reaction
root/src
```

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all`
  - Want: `root/lcov.info`
  - Actual: `root/find_unique_interval/lcov.info`

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all --root .`
  - Want: `root/lcov.info`
  - Actual: `root/find_unique_interval/lcov.info`

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all --output-dir target\tarpaulin  `
  - Want: `root/target/tarpaulin/lcov.info`
  - Actual: `root/find_unique_interval/target/tarpaulin/lcov.info`

# [Workaround :link:](https://github.com/dkudlek/tarpaulin/commit/d597f7b394e8fed38cc0192546232923c970ebf4)
- Force tarpaulin to read the current directory during configuration stage 
- Use the root directory in `lcov.rs` for a relative path 
- Combine it with `output_dir`
- Use `--output-dir target\tarpaulin` to aovid an empty out_dir because it will try to get the current directory if empty
- Working Example: `cargo tarpaulin --ignore-tests --out Lcov --all --output-dir target\tarpaulin`
- Still Failing Example: Run `cargo tarpaulin --ignore-tests --out Lcov --all` 
  - Want: `root/lcov.info`
  - Actual: `root/find_unique_interval//lcov.info`

# Software versions
- rustc 1.64.0 (a55dd71d5 2022-09-19)
- cargo 1.64.0 (387270bc7 2022-09-16)
- cargo-tarpaulin version: 0.23.1
- Windows 10: 21H2 (Build 19044.2251)
- VS Code: 1.73.1
- Coverage Gutters v2.10.2

**Comment by xd009642** [comment] 2023-01-13 20:57
This may be fixed in the develop branch if you don't mind giving it a test (hopefully by fixing your other issue earlier in the week)

**Comment by dkudlek** [comment] 2023-01-14 08:42
I checked out develop (16bbf71ac1a2ba57b010045eaea3330f6bef4bd5), but this issue still persists.  I ran the the same actions as in the opening post and got the same results.
But thanks already for the hard work on the UNC issue!

**Comment by AntoniosBarotsis** [comment] 2023-01-17 00:38
I am having the same issue, was about to open an issue.

The dev branch is indeed not working for me either, @dkudlek's workaround perhaps works for his use case but the issue is not `lcov` specific.


What I did instead is set `output_dir` to the root by default. I have no idea if this breaks something else that I did not consider but the output is correct for me now.

**Comment by xd009642** [comment] 2023-01-21 13:33
So this branch may fix it `fix/report-dirs-windows` (PR: https://github.com/xd009642/tarpaulin/pull/1190). I'll need to boot my windows laptop up some point today to find out but if you test it first that also works :ok_hand:

**Comment by AntoniosBarotsis** [comment] 2023-01-21 13:53
This is the same as what I did in the referenced commit above so yes it should work. The only "catch" was some prints that seemed to still be using current dir although I'm not sure if that got fixed elsewhere. 

I'll be home in a few minutes and I can try it then

**Comment by xd009642** [comment] 2023-01-21 14:00
Oh doh I missed that commit! I'll probably check it in an hour or 2

**Comment by AntoniosBarotsis** [comment] 2023-01-21 14:47
Yes so it is essentially the same as with my commit, the output directory is correct but the info log is wrong.

Running in [this](https://github.com/AntoniosBarotsis/qr-rs/tree/dev) project outputs the following:

```
Jan 21 15:40:23.919  INFO cargo_tarpaulin::report: Coverage Results:
|| Tested/Total Lines:
|| ..\cli\src\error.rs: 0/8 +0.00%
|| ..\cli\src\main.rs: 0/25 +0.00%
|| ..\common\src\lib.rs: 7/7 +0.00%
|| ..\common\src\logos.rs: 9/13 -30.77%
|| ..\lib\src\error.rs: 3/11 +0.00%
|| ..\lib\src\lib.rs: 87/87 +0.00%
|| src\endpoints.rs: 21/21 +0.00%
|| src\error.rs: 11/11 +0.00%
|| src\main.rs: 0/2 +0.00%
||
74.59% coverage, 138/185 lines covered, -8.84% change in coverage
```

Notice how the prints seem to be made inside of one of the project's crates (the `server` in my case which is likely the last one to run seeing as how that's where the report would be dropped prior to this fix).

The prints seem to happen in [this](https://github.com/xd009642/tarpaulin/blob/b62c1344a5666d7294290ac0a827b0ab834ba276/src/report/mod.rs#L108-L130) function but the issue is likely with how some iteration happens.

**Comment by xd009642** [comment] 2023-01-21 16:55
I've realised what the printing is, it's related to me getting the paths from the llvm coverage files, hopefully a quick fix now I know where it's coming from. Then I'll aim to add this in, then fix globs for windows and cut a new release

**Comment by xd009642** [comment] 2023-01-21 17:17
And I've found it, once CI passes I'll merge meanwhile onward to globs!

**Comment by xd009642** [comment] 2023-01-21 18:08
And it's merged, just gonna close this now - and there should be a new tarpaulin version before weekend is over :smile:

**Closed by xd009642** 2023-01-21 18:08 UTC

**Comment by dkudlek** [comment] 2023-01-22 19:18
I checked out 959c8bea76c5752b5a7aa4ebde28d974cc230190 and 1f40d9a84b7626f6205e63da61be2f7022738d03 on `develop`. My first two test cases work. This would work for me. ✔️ 

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all`
    - Want: `root/lcov.info`
    - Actual: `root/lcov.info`  :heavy_check_mark:

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all --root .`
    - Want: `root/lcov.info`
    - Actual: `root/lcov.info` :heavy_check_mark:


For the sake of completeness, the last use case still fails. Trying to change the output directory. 

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all --output-dir target\tarpaulin`  
    - Want: `root/target/tarpaulin/lcov.info`
    - Actual: `root/find_unique_interval/target/tarpaulin/lcov.info` ✖️

- Action: Run `cargo tarpaulin --ignore-tests --out Lcov --all --root . --output-dir target\tarpaulin`  
    - Want: `root/target/tarpaulin/lcov.info`
    - Actual: `root/find_unique_interval/target/tarpaulin/lcov.info` ✖️

**Comment by xd009642** [comment] 2023-01-22 21:14
I think I see it - this should fix it https://github.com/xd009642/tarpaulin/pull/1193 @dkudlek

**Comment by dkudlek** [comment] 2023-01-23 05:47
Looks good to me! 

- `cargo tarpaulin --ignore-tests --out Lcov --all`
    - expect: `root/lcov.info`
    - get: `root/lcov.info` ✔️ 

- `cargo tarpaulin --ignore-tests --out Lcov --all --root .`
    - expect: `root/lcov.info`
    - get: `root/lcov.info` ✔️ 

 - `cargo tarpaulin --ignore-tests --out Lcov --all --output-dir target\tarpaulin` 
     - expect: `root/target/tarpaulin/lcov.info`
     - get: `root/target/tarpaulin/lcov.info` ✔️ 
 
 
 - `cargo tarpaulin --ignore-tests --out Lcov --all --root . --output-dir target\tarpaulin`
     - expect: `root/target/tarpaulin/lcov.info`
     - get: `root/target/tarpaulin/lcov.info` ✔️
