### ISSUE TITLE
Internal compiler error on compiling of proptest v0.8.7

### ISSUE THREAD

**Issue by plokhotnyuk** [xd009642/tarpaulin#234] opened 2019-05-27 14:00 UTC
Steps to reproduce:
1. Clone `https://github.com/Alexhuszagh/rust-lexical`
2. Enter to core: `cd rust-lexical/lexical-core`
3. Run tests with coverage: `cargo tarpaulin -v -o Html`

Expected:
The `tarpaulin-report.html` file in the current directory.

Actually:
Compilation error:
```
andriy@notebook:~/Projects/com/github/Alexhuszagh/rust-lexical/lexical-core$ cargo tarpaulin -v -o Html
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
   Compiling proptest v0.8.7
error: internal compiler error: src/librustc/traits/codegen/mod.rs:58: Encountered error `Unimplemented` selecting `Binder(<core::char::DecodeUtf16<<std::vec::Vec<u16> as core::iter::IntoIterator>::IntoIter> as arbitrary::traits::Arbitrary>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.2 (6c2484dc3 2019-05-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C relocation-model=dynamic-no-pic -C link-dead-code -C opt-level=0 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

[ERROR tarpaulin] Failed to compile tests! Error: Could not compile `proptest`.
```

**Comment by xd009642** [comment] 2019-05-27 16:19
This is a known error and there are one or two issues in the rust repo for it. I'm going to close this as a duplicate of https://github.com/xd009642/tarpaulin/issues/161 which you can follow for any updates

**Closed by xd009642** 2019-05-27 16:19 UTC
Labels: duplicate
