### ISSUE TITLE
Failed to collect coverage when killing spawned server process in test

### ISSUE THREAD

**Issue by ChrisGreenaway** [xd009642/tarpaulin#953] opened 2022-02-09 14:04 UTC
**Describe the bug**
I have a binary project where the binary is a server-like process - in other words, it comes up and stays up. I have a test that spawns the binary, makes a request to the server then SIGTERMs the process to clean-up - releasing open ports, etc.

Killing the process seems to interfere with tarpaulin's ability to record coverage. The test seems to run fine, but I get the error:
```
ERROR cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: Attempting to handle tarpaulin being signaled
```

I have used `--follow-exec` and `--forward` to invoke tarpaulin.

If I remove the kill signal then everything is fine, except that the tests can't be re-run because the server process is there holding  onto the ports which are needed for a second child process to start.

**To Reproduce**
Tarpaulin command:
```
cargo tarpaulin --follow-exec --forward
```

Project as follows:
```
==> Cargo.toml <==
[package]
name = "tarpaulin_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[dev-dependencies]
http = "0.2.6"
hyper = "0.14.16"
nix = "0.23.1"
test_bin = "0.4.0"

==> src/main.rs <==
use warp::Filter;

#[tokio::main]
async fn main() {
    let hello = warp::path("hello")
        .and(warp::get())
        .map(|| String::from("Hello"));

    warp::serve(hello)
        .run(([127, 0, 0, 1], 8080))
        .await;
}

==> tests/integration-tests.rs <==
#[test]
fn spawn_test_and_kill() {
    let _child: ChildWrapper = test_bin::get_test_bin("tarpaulin_test")
    .spawn()
    .unwrap()
    .into();
    
    run_test().unwrap();
}


fn run_test() -> Result<(), tokio::time::error::Elapsed> {
    tokio::runtime::Runtime::new()
        .unwrap()
        .block_on(healthy_or_timeout())
}

async fn healthy_or_timeout() -> Result<(), tokio::time::error::Elapsed> {
    tokio::time::timeout(std::time::Duration::from_secs(5), wait_for_healthy()).await
}

async fn wait_for_healthy() {
    loop {
        if let Ok(response) = http_call().await {
            if response.status() == http::StatusCode::OK {
                return;
            }
        }

        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }
}

async fn http_call() -> Result<hyper::Response<hyper::Body>, hyper::Error> {
    let url = "http://localhost:8080/hello".parse().unwrap();
    let client = hyper::client::Client::new();
    client.get(url).await
}

struct ChildWrapper {
    child: std::process::Child,
}

impl ChildWrapper {
    fn new(child: std::process::Child) -> Self {
        Self {
            child,
        }
    }
}

impl Drop for ChildWrapper {
    fn drop(&mut self) {
        let pid = self.child.id();
        let pid = nix::unistd::Pid::from_raw(pid.try_into().unwrap());
        let _ = nix::sys::signal::kill(pid, nix::sys::signal::Signal::SIGTERM);
    }
}

impl From<std::process::Child> for ChildWrapper {
    fn from(child: std::process::Child) -> Self {
        ChildWrapper::new(child)
    }
}
```

**Expected behavior**
I expected tarpaulin to collect test coverage.

**Comment by boustrophedon** [comment] 2022-02-23 07:48
I can start a new issue for this but it seems like it might be related (but not because the test is being killed):

I'm having issues where coverage in subprocesses spawned by std::process::Command isn't being followed with --follow-exec.

Here's the code: https://github.com/boustrophedon/extrasafe/blob/tarpaulin_missing_coverage_subprocess/examples/ipc_server_with_database.rs#L41
And here's the CI run: https://github.com/boustrophedon/extrasafe/actions/runs/1885986632
Coveralls link: 

There are several overlapping things happening here:

- The file is an example inside examples/
- I added a small shim to call main() from a test inside the example
- The project itself deals with seccomp, so it's possible that the seccomp filter is interfering with following the execution of subprocesses.

I'll try over the next few days to see if I can get a minimal reproduction.

**Comment by xd009642** [comment] 2022-03-06 15:23
So I've figured out what it fully is thanks to the MRE provided via #966 solving one of the two issues present. The other issue I started to have some inkling of when looking at my developer traces. And these were confirmed via  the strace developer docs (README-linux-ptrace.md):

> PTRACE_EVENT_VFORK - stop before return from vfork/clone+CLONE_VFORK.
When tracee is continued after this, it will wait for child to
exit/exec before continuing its execution (IOW: usual behavior on
vfork).

My own traces that lead me to this (partially showing off my coloured execution traces :upside_down_face:):

![image](https://user-images.githubusercontent.com/3472518/156929555-c9845612-88f4-4588-b3da-e61312fcb09d.png)

I'm going to change tarpaulin to try and explicitly continue the parent via ptrace when exec is traced and see how that impacts it, it'll just take some extra work as currently the assumption in the tracing state machine is one ptrace action per ptrace event. But I hope to have this done today or next week and know if it'll solve the issue

**Comment by xd009642** [comment] 2022-03-06 23:43
Pending some documentation updates in the code comments to explain some of the decisions and figuring out nightly CI failure this seems pretty much there. So if have any time to try out the `issue/process-kill-953` branch and let me know how it works for you that would be appreciated :smile:

**Comment by ChrisGreenaway** [comment] 2022-03-07 09:41
Tried it. It works great. Thanks.

**Comment by xd009642** [comment] 2022-03-13 11:32
So still working on fixing the last remaining issue, essentially it happens about 4% of runs on the follow_exe integration on nightly and <3% on stable. Hopefully, this is the last issue to solve before I can get this merged and released :pray:   

![Screenshot from 2022-03-12 16-45-55](https://user-images.githubusercontent.com/3472518/158057369-b35e2613-5413-401a-8fa8-d329e109de96.png)

**Comment by xd009642** [comment] 2022-03-20 15:57
And I've solved it in a "reasonable" manner, I found that over 3500 runs with `--test-threads=1` the issue never presented so if `--follow-exec` is set and the user isn't explicitly overriding the --test-threads I automatically set the test-threads to 1. Just waiting for final CI run to pass, then there's another PR I want to merge and I'll do a release before the end of the day

**Comment by xd009642** [comment] 2022-03-20 18:22
Release 0.20.0 will be out once CI finishes with the fix for this issue :+1:

**Closed by xd009642** 2022-03-20 18:22 UTC
