### ISSUE TITLE
Nightly mandatory?

### ISSUE THREAD

**Issue by alexschrod** [xd009642/tarpaulin#512] opened 2020-07-28 04:45 UTC
It's been two months since my last build; I just did a version bump to release a change I accepted a while back, and something that has happened between then and now has caused my tarpaulin step to suddenly fail. Here's the output from two months ago:
```
Run actions-rs/tarpaulin@v0.1
[tarpaulin] downloading cargo-tarpaulin from https://github.com/xd009642/tarpaulin/releases/download/0.13.2/cargo-tarpaulin-0.13.2-travis.tar.gz
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/e13e7765-635b-4569-bb13-77459cfa3805 -f /home/runner/work/_temp/1b854705-6197-41dc-ad1a-3586ba3746b7
[tarpaulin] running tests with coverage tracking
/usr/share/rust/.cargo/bin/cargo tarpaulin --out Xml --run-types Doctests --run-types Tests
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/runner/work/serde-tcod-config-parser/serde-tcod-config-parser/target/debug/serde_tcod_config_parser-f179f45497b1a7bb

running 3 tests
test lexer::tests::char_oct ... ok
test lexer::tests::char_hex ... ok
test lexer::tests::char_special ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/de/mod.rs: 0/122
|| src/de/primitive_sequence_access.rs: 0/14
|| src/de/struct_internal_access.rs: 0/42
|| src/de/struct_sequence_access.rs: 0/11
|| src/lexer.rs: 28/46
|| 
11.91% coverage, 28/235 lines covered
```
and here's the output from yesterday:
```
[tarpaulin] downloading cargo-tarpaulin from https://github.com/xd009642/tarpaulin/releases/download/0.14.2/cargo-tarpaulin-0.14.2-travis.tar.gz
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/745ac693-1fb2-4f0b-b7a5-4bf3075cbcf3 -f /home/runner/work/_temp/0d9d8e01-001d-4fa4-be5c-c8c67e7f37e2
[tarpaulin] running tests with coverage tracking
/usr/share/rust/.cargo/bin/cargo tarpaulin --out Xml --run-types Doctests --run-types Tests
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
[ERROR tarpaulin] Building doctests failed
[ERROR tarpaulin] Cargo failed to run! Error: Building doctest failed
Error: "Cargo failed to run! Error: Building doctest failed"
##[error]The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 1
```
on my end I've changed nothing but the version line in `Cargo.toml` between these two builds; but it looks like something between 0.13.2 and 0.14.2 broke the action.

**Comment by xd009642** [comment] 2020-07-28 07:15
You must have added your first doc test to the project. None are ran in the first run and doc test coverage is nightly only as it relies on an unstable flag to persist the doctests instead of just deleting them

**Comment by alexschrod** [comment] 2020-07-28 10:00
I promise you, the only change I made was to Cargo.toml between these two runs. You can see the green checkmark on the second-to-last commit and the red X on the last commit here: https://github.com/alexschrod/serde-tcod-config-parser/commits/master

**Comment by xd009642** [comment] 2020-07-28 10:49
Ah I've got it. In 0.14.2 changelog `Return an error if a doctest fails to compile` yeah so previously if your doctests failed to compile (or couldn't be ran) because you tried to get coverage for them using a non-nightly compiler (or of course if there was an error in the doctests) it just silently ignored them. 

So you can remove `--run-types Doctests` and get the same results as you were before. Or move to nightly and get doctest coverage as well.

**Comment by xd009642** [comment] 2020-07-29 21:29
I'm going to close this as it seems resolved but feel free to reopen if you have any follow up questions on this :slightly_smiling_face:

**Closed by xd009642** 2020-07-29 21:29 UTC

**Comment by bryango** [comment] 2024-08-29 07:36
> doc test coverage is nightly only as it relies on an unstable flag to persist the doctests instead of just deleting them

I think this is still the case, but it's not documented AFAIK. For me `cargo tarpaulin --doc`
- works with `cargo 1.82.0-nightly (8f40fc59f 2024-08-21)`, but
- does not work with `cargo 1.80.0 (376290515 2024-07-16)`

Shouldn't this be documented, either in `README.md` or `cargo tarpaulin --help`? I can make a PR if desired!

**Comment by xd009642** [comment] 2024-08-29 07:47
This is documented in the `TROUBLESHOOTING.md` file. But also tarpaulin will see if you have rustup installed and add a `+nightly` if you do otherwise print out an error message that should be clear enough.

I've never had anyone raise an issue regarding confusion on this and generally my "what goes in the readme" is determined by what's causing people issues so I gather it's clear for most people and doesn't need a PR :man_shrugging:

**Comment by bryango** [comment] 2024-08-29 08:14
Ah interesting! Thank you! I think the reason is that I was using `cargo-tarpaulin` through `nix run`:
```bash
nix run nixpkgs#cargo-tarpaulin -- --doc
```
Somehow this triggers the compilation failure, which I can no longer reproduce once installing `cargo-tarpaulin` in my profile. Sorry for the noise!
