### ISSUE TITLE
tarpaulin returns error code 0 even when test fails

### ISSUE THREAD

**Issue by breeswish** [xd009642/tarpaulin#119] opened 2018-06-25 07:43 UTC
My project takes a long time to run tests (about 30 minutes). tarpaulin does not fail when test fails so that currently I have two steps in CI, `run test` and `tarpaulin`, which doubles my CI build time. I think it would be better if I don't need a standalone `run test` step when I'm running tests in tarpaulin, while preserving the behavior to fail the CI if test fails.

**Comment by codeworm96** [comment] 2018-06-25 16:13
+1

Also, if some tests fail, the coverage result is not accurate. I would like to detect these cases, so that I can avoid uploading them to codecov/coveralls.

**Comment by xd009642** [comment] 2018-06-25 18:22
I'll add something to return 1 if a test fails. Although, the coverage results are accurate because they return what parts of the code were covered, it makes sense that a regression that's caught by tests could impact coverage.

You will be able to do this already with codecov once I've implemented returning 1 on test failure by only triggering the codecov bash file on a successful run, I'll look into coveralls.

**Comment by xd009642** [comment] 2018-06-29 22:50
I've got tarpaulin returning -1 on a test failure now and it's merged and in develop so I'll close this issue. 

Feel free to let me know if that's not enough to avoid a coveralls upload and whether a flag to suppress the upload is required and I'll reopen the issue and look into popping something in (though it might be after the big report module rework).

**Closed by xd009642** 2018-06-29 22:50 UTC
Labels: enhancement
